import os
import resend

resend.api_key = os.getenv("RESEND_API_KEY")


def send_email(recipient: str, summary: str) -> dict:
    html_body = f"""
    <div style="font-family: Arial, sans-serif; max-width: 700px; margin: auto; padding: 20px;">
        <h2 style="color: #4f46e5;">📊 Sales Insight Report — Rabbitt AI</h2>
        <hr style="border: 1px solid #e5e7eb;" />
        <div style="line-height: 1.8; color: #374151; white-space: pre-line;">
            {summary}
        </div>
        <hr style="border: 1px solid #e5e7eb; margin-top: 30px;" />
        <p style="color: #9ca3af; font-size: 12px;">
            Generated by Sales Insight Automator | Rabbitt AI
        </p>
    </div>
    """

    params = {
        "from": "Sales Bot <onboarding@resend.dev>",
        "to": [recipient],
        "subject": "📊 Your Q1 Sales Insight Report — Rabbitt AI",
        "html": html_body,
    }

    return resend.Emails.send(params)